export const CREATE_EXERCISE_REQUEST = 'CREATE_EXERCISE_REQUEST';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_FAILURE = 'CREATE_EXERCISE_FAILURE';
export const REMOVE_EXERCISE_REQUEST = 'REMOVE_EXERCISE_REQUEST';
export const REMOVE_EXERCISE_SUCCESS = 'REMOVE_EXERCISE_SUCCESS';
export const REMOVE_EXERCISE_FAILURE = 'REMOVE_EXERCISE_FAILURE';
